### PR TITLE
Support for easy-connect

### PR DESCRIPTION
**Pull request by JanneKiiskila**
The helper library easy-connect offers a way to more abstractly
define the networks being used.

### CODE REVIEW

**Comment by geky** [comment]
This raises the question do we want users to use easy-connect in their product. When asked previously, the answer was no, because it adds unnecessary dependencies.

The goal of the example shouldn't be to make OOB easy, but to make building a new product easy. Using easy-connect here hides the interface that a user needs to interact with if they are needing to use their own network stack or a library not supported by easy-connect.

IMO we should have a separate example for easy-connect. It's probably even a good idea to point to the easy-connect example from this example's readme and use easy-connect in other examples demonstrating different APIs (for example client). But using easy-connect in this example is counterproductive for the goal of demonstrating the socket API.

**Review by SeppoTakalo — CHANGES_REQUESTED** [review]
No, we are already working on getting rid of Easy Connect by supporting "default interfaces" in Mbed OS.

I will not add any dependencies here for external libraries (unless WiFi modules).

**Comment by JanneKiiskila** [comment]
@SeppoTakalo  - you will not get rid of easy-connect (or some other variant of it), due to the fact the the WiFi-stacks *are not included in Mbed OS!*

You must somewhere, somehow have the `*.lib` references that pull those drivers in. Would it make sense to pull all of them in one go (and fix the memory issue we're having) and just keep that one common place up-to-date with "known to be OK version of the drivers" vs. having multiple repos with MULTIPLE `'.lib` pulls and everyone trying to keep those in place? 

Especially since none of the WiFi repos seem to have any PR checks in them. @teetak01 at least has done PR checks for the `easy-connect` repo!

Modifications done for the easy-connect do not in any way undermine or change the sockets usage.

**Comment by JanneKiiskila** [comment]
We should @SeppoTakalo  make easy-connect v2.0 that uses the default interfaces, rather than stop using easy-connect. That would change the role of easy-connect to be more like "I collect the network interfaces/repos into one place". So, in the end - you will have to pull it in here. We can do that with easy-connect 2.0, though.

**Comment by geky** [comment]
> You must somewhere, somehow have the *.lib references that pull those drivers in. Would it make sense to pull all of them in one go (and fix the memory issue we're having) and just keep that one common place up-to-date with "known to be OK version of the drivers" vs. having multiple repos with MULTIPLE '.lib pulls and everyone trying to keep those in place?

This doesn't make sense from a user's perspective. A user will have 1 wifi chip and 1 board. Why should the download 8 different libraries?

What if they have their own wifi chip + their own wifi driver? The example as is allows them to easily plug in their driver to see what it would look like inside of mbed-os.

> Especially since none of the WiFi repos seem to have any PR checks in them. @teetak01 at least has done PR checks for the easy-connect repo!

We should add CI to the wifi repos :)

Look at it this way, now we can add very aggressive tests running against UBLOX wifi without having to wait for esp8266 to catch up.

**Pull request closed without merging**
