### PR TITLE
CMake: Fix missing ISM43362 WiFi driver

### PR DESCRIPTION
**Pull request by LDong-Arm**

### CODE REVIEW

**Review by 0xc0170 — APPROVED** [review]

**Comment by LDong-Arm** [comment]
@0xc0170 @jeromecoutant I just updated README with Mbed CLI 2 instructions too.

**Review by jeromecoutant — APPROVED** [review]

**Comment by LDong-Arm** [comment]
@ARMmbed/mbed-os-connectivity FYI

**Comment by LDong-Arm** [comment]
I'm merging it as it's a simple fix and approved by two reviewers.

**Comment by jeromecoutant** [comment]
Why this PR is not part of latest 6.15 label ?

**Comment by 0xc0170** [comment]
It is on master, part of 6.15 release update.

**Pull request merged**
